name: CICD Workflow to test
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.5.3
      - name: Install dependencies
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test
